# Generated by Django 4.2.4 on 2023-08-30 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(help_text='Unique ID to identify a movie or a serie', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('movie', 'MOVIE'), ('serie', 'SERIE')], default='movie', help_text='Type', max_length=10)),
                ('visualizations', models.PositiveIntegerField()),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5, message='El valor debe ser menor o igual a 5.'), django.core.validators.MinValueValidator(1, message='El valor debe ser mayor o igual a 1.')])),
            ],
        ),
    ]
