# Generated by Django 4.2.4 on 2023-08-31 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5.0, message='El valor debe ser menor o igual a 5.'), django.core.validators.MinValueValidator(0.0, message='El valor debe ser mayor o igual a 1.')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='visualizations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
