# Generated by Django 4.2.4 on 2023-09-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_score_alter_movie_visualizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='qty_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
